[package]
name = "measure_install_code"
version = "0.1.0"
edition = "2021"

[dependencies]
ic-agent = "0.31"
ic-utils = "0.31"
candid = "0.10"
clap = { version = "4.4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
regex = "1"
